AcunMedyaHospitalProject/Controllers/UILayoutController.cs
using AcunMedyaHospitalProject.Context;
using AcunMedyaHospitalProject.Entities;
using AcunMedyaHospitalProject.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaHospitalProject.Controllers
{
    public class UILayoutController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();
        // GET: UILayout
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PartialHeader()
        {
            return PartialView();
        }
        public ActionResult PartialSiteHeader()
        {
            return PartialView();
        }
        public ActionResult PartialFooter()
        {
            return PartialView();
        }
        public ActionResult PartialAppointmentForm()
        {
            TempData["Departments"] = DepartmentHelper.GetDepartments();
            return PartialView();
        }
        public ActionResult PartialScripts()
        {
            return PartialView();
        }
        [HttpGet]
        public JsonResult GetDoctorByDepartmentId(int departmentId)
        {
            var doctors = db.Doctors.Where(x => x.DepartmentId == departmentId)
                .Select(x => new { x.Id, x.FirstName, x.LastName })
                .ToList();
            return Json(doctors, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult MakeAppointment(Appointment appointment)
        {
            appointment.Status = Enums.AppointmentStatus.Pending;
            appointment.CreatedDate = DateTime.UtcNow;

            db.Appointments.Add(appointment);
            db.SaveChanges();
            return RedirectToAction("Index","Default");
        }

    }

}

AcunMedyaHospitalProject/Views/UILayout/Index.cshtml
@{ 
    Layout = null;
}

<!doctype html>
<html class="no-js" lang="zxx">

@Html.Action("PartialHeader","UILayout")

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    <!-- header-start -->
    @Html.Action("PartialSiteHeader","UILayout")
    <!-- header-end -->
    @RenderBody()
    <!-- footer start -->
    @Html.Action("PartialFooter", "UILayout")
    <!-- footer end  -->
    <!-- link that opens popup -->
    <!-- form itself end-->
    @Html.Action("PartialAppointmentForm", "UILayout")
    <!-- form itself end -->
    <!-- JS here -->
    @Html.Action("PartialScripts", "UILayout")
</body>

</html>

AcunMedyaHospitalProject/Views/UILayout/PartialAppointmentForm.cshtml
@model AcunMedyaHospitalProject.Entities.Appointment
<form action="/UILayout/MakeAppointment"  method="post" id="test-form" class="white-popup-block mfp-hide">
    <div class="popup_box ">
        <div class="popup_inner">
            <h3>Randevu Al</h3>
            <form action="#">
                <div class="row">
                    <div class="col-xl-6">
                        <input id="datetime-local" name="Date" placeholder="Tarih Seçin">
                    </div>
                    <div class="col-xl-6">
                        <input type="time" id="timePicker" name="Time" placeholder="Saat">
                    </div>
                    <div class="col-xl-6">
                        @Html.DropDownList("Department", (SelectList)TempData["Departments"], "Bölüm Seçin", new { @class = "nice-select form-select wide", @id = "department-select" })
                    </div>
                    <div class="col-xl-6">
                        <select class="nice-select form-select wide" name="DoctorId" id="doctor-select">
                            <option data-display="Doctors">Doktor seçin</option>
                        </select>
                    </div>
                    <div class="col-xl-6">
                        <input type="text" name="PatientFirstName" placeholder="Hasta Adı">
                    </div>
                    <div class="col-xl-6">
                        <input type="text" name="PatientLastName" placeholder="Hasta Soyadı">
                    </div>
                    <div class="col-xl-6">
                        <input type="text" name="PatientPhone" placeholder="Telefon">
                    </div>
                    <div class="col-xl-12">
                        <input type="email" name="PatientEmail" placeholder="Email">
                    </div>
                    <div class="col-xl-12">
                        <button type="submit" class="boxed-btn3">Randevuyu kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#department-select').change(function () {
            var dId = $(this).val();
            $.ajax({
                url: '@Url.Action("GetDoctorsByDepartmentId","UILayout")',
                type: 'GET',
                data: { departmentId: dId },
                succes: function (data) {
                    var doctorSelect = $('#doctor-select');
                    doctorSelect.empty();
                    doctorSelect.append('<option data-display="Doctors">Doktor seçin</option>')
                    $.each(data, function (index, doctor) {
                        doctorSelect.append('<option value="' + doctor.Id + '">' + doctor.FirstName + ' ' + doctor.LastName+ '</option>');
                    });
                }
            });
        });
    })
</script>

AcunMedyaHospitalProject/Views/UILayout/PartialFooter.cshtml
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="footer_widget">
                        <div class="footer_logo">
                            <a href="#">
                                <img src="/Templates/docmed-master/img/footer_logo.png" alt="">
                            </a>
                        </div>
                        <p>
                            Sağlık hizmetlerinde mükemmelliği hedefliyoruz.
                            Gelişmiş teknolojimiz ve uzman ekibimizle, sağlığınızı en iyi şekilde koruyoruz.
                        </p>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-2 offset-xl-1 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Bölümler
                        </h3>
                        <ul>
                            <li><a href="#">Göz</a></li>
                            <li><a href="#">Diş</a></li>
                            <li><a href="#">Dermatoloji</a></li>
                            <li><a href="#">Kardiyoloji</a></li>
                            <li><a href="#">Nöroloji</a></li>
                        </ul>

                    </div>
                </div>
                <div class="col-xl-2 col-md-6 col-lg-2">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Bağlantılar
                        </h3>
                        <ul>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">İletişim</a></li>
                            <li><a href="#">Randevu</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Address
                        </h3>
                        <p>
                            İstanbul <br>
                            +90 555 55 55 <br>
                            acunmedyahospital@contact.com
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

AcunMedyaHospitalProject/Views/UILayout/PartialHeader.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AcunMedya Hospital</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="/Templates/docmed-master/img/favicon.png">
    <!-- Place favicon.ico in the root directory -->
    <!-- CSS here -->
    <link rel="stylesheet" href="/Templates/docmed-master/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/magnific-popup.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/themify-icons.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/nice-select.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/flaticon.Defaultcss">
    <link rel="stylesheet" href="/Templates/docmed-master/css/gijgo.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/animate.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/slicknav.css">
    <link rel="stylesheet" href="/Templates/docmed-master/css/style.css">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

AcunMedyaHospitalProject/Views/UILayout/PartialScripts.cshtml
<script src="/Templates/docmed-master/js/vendor/modernizr-3.5.0.min.js"></script>
<script src="/Templates/docmed-master/js/vendor/jquery-1.12.4.min.js"></script>
<script src="/Templates/docmed-master/js/popper.min.js"></script>
<script src="/Templates/docmed-master/js/bootstrap.min.js"></script>
<script src="/Templates/docmed-master/js/owl.carousel.min.js"></script>
<script src="/Templates/docmed-master/js/isotope.pkgd.min.js"></script>
<script src="/Templates/docmed-master/js/ajax-form.js"></script>
<script src="/Templates/docmed-master/js/waypoints.min.js"></script>
<script src="/Templates/docmed-master/js/jquery.counterup.min.js"></script>
<script src="/Templates/docmed-master/js/imagesloaded.pkgd.min.js"></script>
<script src="/Templates/docmed-master/js/scrollIt.js"></script>
<script src="/Templates/docmed-master/js/jquery.scrollUp.min.js"></script>
<script src="/Templates/docmed-master/js/wow.min.js"></script>
<script src="/Templates/docmed-master/js/nice-select.min.js"></script>
<script src="/Templates/docmed-master/js/jquery.slicknav.min.js"></script>
<script src="/Templates/docmed-master/js/jquery.magnific-popup.min.js"></script>
<script src="/Templates/docmed-master/js/plugins.js"></script>
<script src="/Templates/docmed-master/js/gijgo.min.js"></script>
<!--contact js-->
<script src="/Templates/docmed-master/js/contact.js"></script>
<script src="/Templates/docmed-master/js/jquery.ajaxchimp.min.js"></script>
<script src="/Templates/docmed-master/js/jquery.form.js"></script>
<script src="/Templates/docmed-master/js/jquery.validate.min.js"></script>
<script src="/Templates/docmed-master/js/mail-script.js"></script>

<script src="/Templates/docmed-master/js/main.js"></script>
<script>
    $('#datepicker').datepicker({
        iconsLibrary: 'fontawesome',
        icons: {
            rightIcon: '<span class="fa fa-caret-down"></span>'
        }
    });
    $('#datepicker2').datepicker({
        iconsLibrary: 'fontawesome',
        icons: {
            rightIcon: '<span class="fa fa-caret-down"></span>'
        }

    });
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
</script>

AcunMedyaHospitalProject/Views/UILayout/PartialSiteHeader.cshtml
<header>
    <div class="header-area ">
        <div class="header-top_area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-md-6 ">
                        <div class="social_media_links">
                            <a href="#">
                                <i class="fa fa-linkedin"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-6">
                        <div class="short_contact_list">
                            <ul>
                                <li><a href="#"> <i class="fa fa-envelope"></i> info@acunmedya.com</a></li>
                                <li><a href="#"> <i class="fa fa-phone"></i> +90 216 333 33 33</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="sticky-header" class="main-header-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="index.html">
                                <img src="img/logo.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a class="active" href="index.html">Ana Sayfa</a></li>
                                    <li><a href="Department.html">Bölümler</a></li>
                                    <li>
                                        <a href="#">blog <i class="ti-angle-down"></i></a>
                                        <ul class="submenu">
                                            <li><a href="blog.html">blog</a></li>
                                            <li><a href="single-blog.html">single-blog</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#">Sayfalar<i class="ti-angle-down"></i></a>
                                        <ul class="submenu">
                                            <li><a href="elements.html">elements</a></li>
                                            <li><a href="about.html">about</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="Doctors.html">Doktorlar</a></li>
                                    <li><a href="contact.html">İletişim</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">
                            <div class="book_btn d-none d-lg-block">
                                <a class="popup-with-form" href="#test-form">Randevu Alın</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>